users <- read.table("~/Desktop/movielens/ml-1m/users.dat", quote="\"", comment.char="");
  View(users);
ratings <- read.csv("~/Desktop/movielens/ml-latest-small/ratings.csv");
  View(ratings);
movies_v2 <- read.csv("~/Desktop/movielens/movies_v2.csv");
  View(movies_v2);
library("ggplot2");
library("grid");
library("plyr");
library("RColorBrewer");

names(users) <- c("userId" , "gender", "age", "occupation", "zipcode");
View(users);
mov <- merge(movies_v2,ratings);

mlDat <- merge(mov,users);
mlDat_user <- ddply(mlDat, ~ userId + age + gender + occupation, summarize,   mean_rating = mean(rating));
agePlot <- ggplot(mlDat_user, aes(age)) + geom_histogram(aes(y = ..density..), binwidth = 1, colour = "black", fill = "white");
agePlot <- agePlot + geom_density(alpha = 0.2, fill = "#FF6666");
print(agePlot);
mlDat_user <- ddply(mlDat, ~ userId + age + gender + occupation, summarize, mean_rating = mean(rating));
agePlot <- ggplot(mlDat_user, aes(age)) + geom_histogram(aes(y = ..density..), binwidth = 50, colour = "black", fill = "white");
agePlot <- agePlot + geom_density(alpha = 0.2, fill = "#FF6666");
print(agePlot);
mlDat_user <- ddply(mlDat, ~ userId + age + gender + occupation, summarize,  mean_rating = mean(rating)) ;
agePlot <- ggplot(mlDat_user, aes(age)) + geom_histogram(aes(y = ..density..),  binwidth = 30, colour = "black", fill = "white");
agePlot <- agePlot + geom_density(alpha = 0.2, fill = "#FF6666");
print(agePlot);
mlDat_user <- ddply(mlDat, ~ userId + age + gender + occupation, summarize,  mean_rating = mean(rating)) ;
agePlot <- ggplot(mlDat_user, aes(age)) + geom_histogram(aes(y = ..density..),  binwidth = 20, colour = "black", fill = "white") ;
agePlot <- agePlot + geom_density(alpha = 0.2, fill = "#FF6666");
print(agePlot);
mlDat_user <- ddply(mlDat, ~ userId + age + gender + occupation, summarize, mean_rating = mean(rating));
agePlot <- ggplot(mlDat_user, aes(age)) + geom_histogram(aes(y = ..density..), binwidth = 10, colour = "black", fill = "white") ;
agePlot <- agePlot + geom_density(alpha = 0.2, fill = "#FF6666") ;
print(agePlot) ;
mlDat_movie <- ddply(mlDat, ~title + release_date + genres, summarize,mean_rating = mean(rating));
datesPlot <- ggplot(mlDat_movie, aes(release_date)) + geom_histogram(aes(y = ..density..),  binwidth = 500, colour = "black", fill = "white");
datesPlot <- datesPlot + geom_density(alpha = 0.2, fill = "#FF6666") ;
print(datesPlot);
datesPlot <- ggplot(mlDat_movie, aes(release_date)) + geom_histogram(aes(y = ..density..), binwidth = 50, colour = "black", fill = "white") ;
datesPlot <- datesPlot + geom_density(alpha = 0.2, fill = "#FF6666") ;
print(datesPlot) ;
datesPlot <- ggplot(mlDat_movie, aes(release_date)) + geom_histogram(aes(y = ..density..), binwidth = 10, colour = "black", fill = "white");
datesPlot <- datesPlot + geom_density(alpha = 0.2, fill = "#FF6666");
print(datesPlot);
datesPlot <- ggplot(mlDat_movie, aes(release_date)) + geom_histogram(aes(y = ..density..), binwidth = 100, colour = "black", fill = "white") ;
datesPlot <- datesPlot + geom_density(alpha = 0.2, fill = "#FF6666") ;
print(datesPlot) ;
datesPlot <- ggplot(mlDat_movie, aes(release_date)) + geom_histogram(aes(y = ..density..), binwidth = 50, colour = "black", fill = "white") ;
datesPlot <- datesPlot + geom_density(alpha = 0.2, fill = "#FF6666");
print(datesPlot);

Age <- read.csv("~/Desktop/movielens/Age.csv");
View(Age);
Occupations <- read.csv("~/Desktop/movielens/Occupations.csv");
View(Occupations);
mlDat_u <- merge(mlDat, Occupations);
mlDat_user <- ddply(mlDat_u, ~ userId + age + gender + occupation_desc, summarize,  mean_rating = mean(rating));
userPlot <- ggplot(mlDat_user, aes(x = reorder(occupation_desc, occupation_desc, function(x) -length(x)), fill = gender)) + geom_bar();
print(userPlot);
userPlot <- userPlot + theme(axis.text.x = element_text(angle = 90, hjust = 1));
userPlot <- userPlot + ylab("number of users") + xlab("occupation");
userPlot <- userPlot + coord_flip();
print(userPlot);
rankPlot <- ggplot(mlDat_user, aes(x = reorder(occupation_desc, occupation_desc, function(x) -length(x)),  mean_rating)) + geom_violin();
rankPlot <- rankPlot + theme(axis.text.x = element_text(angle = 90, hjust = 1));
rankPlot <- rankPlot + ylab("Average rating on Movies") + xlab("occupation");
rankPlot <- rankPlot + coord_flip();
print(rankPlot);
gender_dat <- ddply(mlDat_user, ~occupation_desc, summarize, perc_male = (length(gender[gender == "M"])/length(gender)), counts = -length(userId))
 genderPlot <- ggplot(gender_dat, aes(x = reorder(occupation_desc, counts), perc_male)) geom_bar(stat = "identity");
 genderPlot <- genderPlot + theme(axis.text.x = element_text(angle = 90, hjust = 1));
 genderPlot <- genderPlot + ylab("percent male") + xlab("occupation");
 genderPlot <- genderPlot + coord_flip();
print(genderPlot) ;
 
 agePlot <- ggplot(mlDat_user, aes(x = reorder(occupation_desc, occupation_desc, function(x) -length(x)), age)) + geom_violin();
 agePlot <- agePlot + theme(axis.text.x = element_text(angle = 90, hjust = 1));
 agePlot <- agePlot + ylab("age") + xlab("occupation");
agePlot <- agePlot + coord_flip();
 print(agePlot)